version: '3'
services:
  server1:
    build: ./servidor
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - /tmp/javadir:/tmp/javadir
    environment:
      - nombre=Servidor 1
      - logName=logfile1
      - port=4444
  server2:
    build: ./servidor
    network_mode: bridge
    ports:
      - "4443:4444"
    volumes:
      - /tmp/javadir:/tmp/javadir
    environment:
      - nombre=Servidor 2
      - logName=logfile2
      - port=4444
    #networks:
     # bridge-tutorial-defined:
        #ipv4_address: 172.18.0.1
#networks:
#  bridge-tutorial-defined:
#    driver: bridge
#    name: bridge-tutorial-defined
#    ipam:
#     config:
#      - subnet: 172.18.0.0/16
#      - gateway: 172.18.0.1